
import com.github.sarxos.webcam.Webcam;
import com.github.sarxos.webcam.WebcamPanel;
import com.github.sarxos.webcam.WebcamResolution;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ALEJO
 */
public class Camara extends javax.swing.JFrame {

    /**
     * Creates new form Camara
     */
    
    //Dimensiones que van a tener las fotos 
    int largoCamara = 329;
    int anchoCamara = 294;
    
    //Variables que definen la ruta de almacenamiento y nombre enumerado
    BufferedImage ruta;
    int contador = 0;
    Dimension dimension = new Dimension(largoCamara, anchoCamara);
    Dimension dimension1 = WebcamResolution.VGA.getSize();
    Webcam webcam = Webcam.getDefault();
    WebcamPanel webcamPanel = new WebcamPanel(webcam,dimension,false);
    
    
    public Camara() {
        initComponents();
        setLocationRelativeTo(null); 
        
        webcam.setViewSize(dimension1);
        webcamPanel.setFillArea(true);
        Panel_camara.setLayout(new FlowLayout());
        Panel_camara.add(webcamPanel);
        
        //Colocmaos en el label el nombre de la camara utilizada
        lbl_camaraUtilizada.setText(webcam.toString());
        
        apagarBotones();
    }
    
    //Metodo que mantiene los botones inactivos
    public void apagarBotones(){
        
        btn_apagar.setEnabled(false);
        btn_capturarFoto.setEnabled(false);
        btn_guardar.setEnabled(false);
    }
    
    //Metodo que activa los botones 
    public void prenderBotones(){
        
        btn_apagar.setEnabled(true);
        btn_capturarFoto.setEnabled(true);
        
    }
    
    public void textoDeBotonesCuandoCargaCamara(){
        
        btn_apagar.setText("Iniciando camara...");
        btn_capturarFoto.setText("Iniciando camara...");
        btn_guardar.setText("Iniciando camara...");
        btn_encender.setText("Iniciando camara...");
    }
    
    public void textoDeBotonesCuandoCargoCamara(){
        
        btn_apagar.setText("APAGAR");
        btn_capturarFoto.setText("CAPTURAR FOTO");
        btn_guardar.setText("GUARDAR");
        btn_encender.setText("INICIAR");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_encender = new javax.swing.JButton();
        btn_apagar = new javax.swing.JButton();
        btn_capturarFoto = new javax.swing.JButton();
        btn_guardar = new javax.swing.JButton();
        Panel_camara = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        lbl_vistaFoto = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lbl_camaraUtilizada = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Opciones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 18))); // NOI18N

        btn_encender.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_encender.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ON.png"))); // NOI18N
        btn_encender.setText("INICIAR");
        btn_encender.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_encender.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_encender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_encenderActionPerformed(evt);
            }
        });

        btn_apagar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_apagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/OFF.png"))); // NOI18N
        btn_apagar.setText("APAGAR");
        btn_apagar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_apagar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_apagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_apagarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_apagar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_encender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(btn_encender, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btn_apagar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        btn_capturarFoto.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_capturarFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/CAMERA (1).png"))); // NOI18N
        btn_capturarFoto.setText("CAPTURAR FOTO");
        btn_capturarFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_capturarFotoActionPerformed(evt);
            }
        });

        btn_guardar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/SAVE.png"))); // NOI18N
        btn_guardar.setText("GUARDAR");
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });

        Panel_camara.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout Panel_camaraLayout = new javax.swing.GroupLayout(Panel_camara);
        Panel_camara.setLayout(Panel_camaraLayout);
        Panel_camaraLayout.setHorizontalGroup(
            Panel_camaraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 329, Short.MAX_VALUE)
        );
        Panel_camaraLayout.setVerticalGroup(
            Panel_camaraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 294, Short.MAX_VALUE)
        );

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        lbl_vistaFoto.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Cámara en uso:");

        lbl_camaraUtilizada.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbl_camaraUtilizada.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_camaraUtilizada.setText("-");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(94, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(Panel_camara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(lbl_camaraUtilizada, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btn_capturarFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_vistaFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btn_guardar)
                        .addGap(75, 75, 75))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(Panel_camara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_capturarFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(92, 92, 92)
                                .addComponent(lbl_vistaFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(45, 45, 45)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_camaraUtilizada)))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Metodo boton iniciar
    private void btn_encenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_encenderActionPerformed
        
        textoDeBotonesCuandoCargaCamara();
        
        Thread hilo = new Thread(){
          
            @Override
            public void run(){
                webcamPanel.start();
                prenderBotones();
                textoDeBotonesCuandoCargoCamara();
            }
        };
        
        hilo.setDaemon(true);
        hilo.start();
        btn_encender.setEnabled(false);
        
    }//GEN-LAST:event_btn_encenderActionPerformed

    //Metodo boton apagar
    private void btn_apagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_apagarActionPerformed
        
        webcamPanel.stop();
        apagarBotones();
        btn_encender.setEnabled(true);
        lbl_vistaFoto.setIcon(null);
    }//GEN-LAST:event_btn_apagarActionPerformed

    //Metodo del boton Capturar foto
    private void btn_capturarFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_capturarFotoActionPerformed
        
        btn_capturarFoto.setText("Tomar otra foto");
        btn_guardar.setEnabled(true);
        
        ImageIcon foto;
        foto = new ImageIcon(webcam.getImage());
        //Muestra la foto tomada en el label
        Icon iconoFoto = new ImageIcon(foto.getImage().getScaledInstance(lbl_vistaFoto.getWidth(), lbl_vistaFoto.getHeight(), Image.SCALE_SMOOTH));
        lbl_vistaFoto.setIcon(iconoFoto);
        
        //Asigna la foto tomada a la ruta definida
        ruta = webcam.getImage();
        
        
    }//GEN-LAST:event_btn_capturarFotoActionPerformed

    //Metodo del boton Guardar
    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
        
        int pregunta = JOptionPane.showConfirmDialog(this, "¿Guardar Foto?","Guardar",JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);
        
        if(pregunta == 0){ //Si presionó si entonces...
            
            //Ruta donde se guardaran las fotos
            File salidaImagen = new File("C:\\Recursos academicos\\mis proyectos\\Java\\proyectos netbeans Java\\UsoDeCamara\\fotostomadas\\Foto" + contador +".jpg");
            
            
            try{
                ImageIO.write(ruta, "jpg", salidaImagen);
                JOptionPane.showMessageDialog(this, "Imagen guardada en: " + salidaImagen.getAbsolutePath());
            }catch(Exception e){
                System.out.println("Error:" + e);
            }
            
            lbl_vistaFoto.setIcon(null);
            btn_guardar.setEnabled(false);
            btn_capturarFoto.setText("CAPTURAR FOTO");
            
        }
        contador++;
    }//GEN-LAST:event_btn_guardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Camara.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Camara.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Camara.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Camara.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Camara().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel_camara;
    private javax.swing.JButton btn_apagar;
    private javax.swing.JButton btn_capturarFoto;
    private javax.swing.JButton btn_encender;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbl_camaraUtilizada;
    private javax.swing.JLabel lbl_vistaFoto;
    // End of variables declaration//GEN-END:variables
}
